import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#131315",
        "surface-dim": "#131315",
        "surface-bright": "#39393b",
        "surface-container-lowest": "#0e0e10",
        "surface-container-low": "#1c1b1d",
        "surface-container": "#201f22",
        "surface-container-high": "#2a2a2c",
        "surface-container-highest": "#353437",
        "on-surface": "#e5e1e4",
        "on-surface-variant": "#c3c6d7",
        "inverse-surface": "#e5e1e4",
        "inverse-on-surface": "#313032",
        "outline": "#8d90a0",
        "outline-variant": "#434655",
        "primary": "#b4c5ff",
        "on-primary": "#002a78",
        "primary-container": "#2563eb",
        "on-primary-container": "#eeefff",
        "secondary": "#7bd0ff",
        "on-secondary": "#00354a",
        "secondary-container": "#00a6e0",
        "on-secondary-container": "#00374d",
        "tertiary": "#d0bcff",
        "on-tertiary": "#3c0091",
        "tertiary-container": "#7d4ce7",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "accent-amber": "#FABA37",
        "accent-green": "#4ADE80",
      },
      spacing: {
        "base": "0.25rem",
        "gutter-sm": "0.5rem",
        "gutter-md": "1rem",
        "gutter-lg": "1.5rem",
        "margin-sm": "1rem",
        "margin-md": "1.5rem",
        "margin-lg": "2rem",
        "safe-bottom-stage": "6rem",
      },
      fontSize: {
        "display-hero-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "900" }],
        "headline-title-mobile": ["20px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "body-compact": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lead": ["15px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "section-heading": ["16px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "900" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "700" }],
        "badge-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.18em", fontWeight: "900" }],
      },
    },
  },
  plugins: [],
};
export default config;